#!/usr/bin/env pwsh
# AgentSentry one-shot installer (Windows / PowerShell 7+).
#
# Usage:
#   .\install.ps1                  # interactive
#   .\install.ps1 -NonInteractive  # accept all defaults
#   .\install.ps1 -Preset prod     # use the "prod" preset
#
# What it does (no per-step prompts unless -Interactive):
#   1. Collects answers (profile, providers, redaction, policy pack, port map).
#   2. Generates secrets (admin API key, per-tenant key).
#   3. Writes  .env.agentsentry  +  deploy/docker-compose.generated.yml
#              gateway/config.generated.yaml + control/config.generated.yaml.
#   4. docker compose up -d --build (idempotent).
#   5. Health-waits gateway + control.
#   6. Runs a self-test (policy check).
#   7. Prints final agent-side integration snippets.

[CmdletBinding()]
param(
  [ValidateSet('dev','prod')] [string] $Preset = 'dev',
  [switch] $NonInteractive,
  [switch] $SkipBoot,
  [string] $GatewayPort = '8080',
  [string] $ControlPort = '8081',
  [string] $UiPort      = '3000'
)

$ErrorActionPreference = 'Stop'
$Root = Resolve-Path $PSScriptRoot
Set-Location $Root

function Info($m)  { Write-Host "[i] $m" -ForegroundColor Cyan }
function Ok($m)    { Write-Host "[+] $m" -ForegroundColor Green }
function Warn($m)  { Write-Host "[!] $m" -ForegroundColor Yellow }
function Fail($m)  { Write-Host "[x] $m" -ForegroundColor Red; exit 1 }

function Ask([string]$prompt, [string]$default) {
  if ($NonInteractive) { return $default }
  $a = Read-Host "$prompt [$default]"
  if ([string]::IsNullOrWhiteSpace($a)) { return $default } else { return $a.Trim() }
}
function AskYN([string]$prompt, [bool]$default) {
  $d = if ($default) { 'Y' } else { 'N' }
  if ($NonInteractive) { return $default }
  $a = Read-Host "$prompt [$d/n]"
  if ([string]::IsNullOrWhiteSpace($a)) { return $default }
  return ($a.Trim().ToLower() -in @('y','yes','true','1'))
}
function NewSecret([int]$bytes = 32) {
  $b = New-Object byte[] $bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
  return 'sk_' + ([System.BitConverter]::ToString($b)).Replace('-','').ToLower()
}

# -------------------------------------------------------------------------
Write-Host ''
Write-Host '  ___                  _   ____             _'
Write-Host ' / _ \                | | / ___|  ___ _ __ | |_ _ __ _   _'
Write-Host '/ /_\ \ __ _  ___ _ __| |_\___ \ / _ \  _ \| __|  __| | | |'
Write-Host '|  _  |/ _` |/ _ \  _ \ __|___) |  __/ | | | |_| |  | |_| |'
Write-Host '\_| |_/\__, |\___/_| |_\__|____/ \___|_| |_|\__|_|   \__, |'
Write-Host '        |___/                                         |___/'
Write-Host ''
Info "Installing AgentSentry into $Root"
Write-Host ''

# 1. preflight ------------------------------------------------------------
$missing = @()
foreach ($c in @('docker')) {
  if (-not (Get-Command $c -ErrorAction SilentlyContinue)) { $missing += $c }
}
if ($missing.Count -gt 0) { Fail "missing required tools: $($missing -join ', ')" }
try { docker compose version | Out-Null } catch { Fail "'docker compose' v2 plugin not found" }
Ok 'docker + docker compose detected'

# 2. answers --------------------------------------------------------------
Info 'Collecting configuration. Press Enter to accept the default.'
$orgName    = Ask 'Organization name'                              'Acme'
$adminEmail = Ask 'Admin email (for the audit log)'                'admin@example.com'

$useOpenAI    = AskYN 'Enable OpenAI proxy?'    ($Preset -eq 'dev')
$openAIBase   = if ($useOpenAI) { Ask 'OpenAI base URL' 'https://api.openai.com' } else { '' }

$useAnthropic = AskYN 'Enable Anthropic proxy?' $true
$anthropicBase= if ($useAnthropic) { Ask 'Anthropic base URL' 'https://api.anthropic.com' } else { '' }

$useGemini    = AskYN 'Enable Google Gemini proxy?' $true
$geminiBase   = if ($useGemini) { Ask 'Gemini base URL' 'https://generativelanguage.googleapis.com' } else { '' }

$useAzure     = AskYN 'Enable Azure OpenAI proxy?' $false
$azureBase    = if ($useAzure) { Ask 'Azure OpenAI resource URL (https://<resource>.openai.azure.com)' 'https://YOUR-RESOURCE.openai.azure.com' } else { '' }

$redactLevel  = Ask 'Redaction level (off|standard|strict)' 'standard'
$policyPack   = Ask 'Starter policy pack (open|standard|strict)' ($(if ($Preset -eq 'prod') {'strict'} else {'standard'}))

$adminKey  = NewSecret 32
$tenantKey = NewSecret 32
Ok 'Generated admin + tenant API keys'

# 3. write .env -----------------------------------------------------------
$envFile = Join-Path $Root '.env.agentsentry'
@"
# Auto-generated by install.ps1 on $(Get-Date -Format o)
# Do NOT commit. Treat the keys below as production secrets.
SENTRY_ORG_NAME=$orgName
SENTRY_ADMIN_EMAIL=$adminEmail
SENTRY_ADMIN_API_KEY=$adminKey
SENTRY_TENANT_API_KEY=$tenantKey

SENTRY_GATEWAY_PORT=$GatewayPort
SENTRY_CONTROL_PORT=$ControlPort
SENTRY_UI_PORT=$UiPort

SENTRY_REDACT_LEVEL=$redactLevel
SENTRY_POLICY_PACK=$policyPack

SENTRY_GW_OPENAI_BASE_URL=$openAIBase
SENTRY_GW_ANTHROPIC_BASE_URL=$anthropicBase
SENTRY_GW_GEMINI_BASE_URL=$geminiBase
SENTRY_GW_AZURE_BASE_URL=$azureBase
"@ | Set-Content -Path $envFile -Encoding utf8
Ok "Wrote $envFile"

# 4. render configs -------------------------------------------------------
$enablePii     = $redactLevel -ne 'off'
$enableSecrets = $redactLevel -ne 'off'

$upstreams = @()
if ($useOpenAI)    { $upstreams += "  openai:`n    base_url: `"$openAIBase`"" }
if ($useAnthropic) { $upstreams += "  anthropic:`n    base_url: `"$anthropicBase`"" }
if ($useGemini)    { $upstreams += "  gemini:`n    base_url: `"$geminiBase`"" }
if ($useAzure)     { $upstreams += "  azure:`n    base_url: `"$azureBase`"" }

@"
# generated by install.ps1 -- safe to regenerate
listen_addr: "0.0.0.0:8080"
control_plane_url: "http://control:8081"
api_key: "$adminKey"
poll_interval_seconds: 10

redact:
  enable_pii:     $($enablePii.ToString().ToLower())
  enable_secrets: $($enableSecrets.ToString().ToLower())

upstreams:
$($upstreams -join "`n")
"@ | Set-Content -Path (Join-Path $Root 'gateway/config.generated.yaml') -Encoding utf8
Ok 'Wrote gateway/config.generated.yaml'

@"
# generated by install.ps1 -- safe to regenerate
listen_addr: ":8081"
postgres_dsn: "postgres://sentry:sentry@postgres:5432/sentry?sslmode=disable"
clickhouse_dsn: "clickhouse://default:@clickhouse:9000/sentry"
dev_api_key: "$adminKey"
seed_demo_data: $($(if ($Preset -eq 'dev') {'true'} else {'false'}))
policy_pack: "$policyPack"
"@ | Set-Content -Path (Join-Path $Root 'control/config.generated.yaml') -Encoding utf8
Ok 'Wrote control/config.generated.yaml'

# 5. render compose override ---------------------------------------------
@"
# generated by install.ps1 -- merged with deploy/docker-compose.dev.yml
services:
  control:
    environment:
      SENTRY_DEV_API_KEY: "$adminKey"
      SENTRY_SEED_DEMO:   "$($(if ($Preset -eq 'dev') {'true'} else {'false'}))"
      SENTRY_POLICY_PACK: "$policyPack"
    ports: ["${ControlPort}:8081"]
  gateway:
    environment:
      SENTRY_GW_CONTROL_URL: "http://control:8081"
      SENTRY_GW_API_KEY:     "$adminKey"
      SENTRY_GW_OPENAI_BASE_URL:    "$openAIBase"
      SENTRY_GW_ANTHROPIC_BASE_URL: "$anthropicBase"
      SENTRY_GW_GEMINI_BASE_URL:    "$geminiBase"
      SENTRY_GW_AZURE_BASE_URL:     "$azureBase"
      RUST_LOG: "info"
    ports: ["${GatewayPort}:8080"]
  ui:
    environment:
      CONTROL_API_URL: "http://control:8081"
      CONTROL_API_KEY: "$adminKey"
    ports: ["${UiPort}:3000"]
"@ | Set-Content -Path (Join-Path $Root 'deploy/docker-compose.generated.yml') -Encoding utf8
Ok 'Wrote deploy/docker-compose.generated.yml'

if ($SkipBoot) { Ok 'Skipping boot (-SkipBoot).'; exit 0 }

# 6. boot ----------------------------------------------------------------
Info 'Booting docker stack (this builds the first time, ~3-5 min)...'
& docker compose `
  -f deploy/docker-compose.dev.yml `
  -f deploy/docker-compose.generated.yml `
  up -d --build
if ($LASTEXITCODE -ne 0) { Fail 'docker compose failed' }

# 7. wait health --------------------------------------------------------
function WaitHttp([string]$url, [int]$timeoutSec = 120) {
  $deadline = (Get-Date).AddSeconds($timeoutSec)
  while ((Get-Date) -lt $deadline) {
    try {
      $r = Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 2
      if ($r.StatusCode -lt 500) { return $true }
    } catch { Start-Sleep 2 }
  }
  return $false
}
Info 'Waiting for control plane...'
if (-not (WaitHttp "http://localhost:$ControlPort/v1/health")) { Fail 'control plane never came up' }
Ok 'Control plane healthy'
Info 'Waiting for gateway...'
if (-not (WaitHttp "http://localhost:$GatewayPort/healthz"))   { Fail 'gateway never came up' }
Ok 'Gateway healthy'

# 8. self-test ----------------------------------------------------------
Info 'Self-test: sending a policy probe through the gateway...'
try {
  $body = @{ package='agentsentry.llm_call'; input=@{ request=@{ body=@{ probe=$true } } } } | ConvertTo-Json -Depth 5
  $null = Invoke-RestMethod -Method POST -Uri "http://localhost:$GatewayPort/v1/policy/check" `
    -ContentType 'application/json' -Body $body `
    -Headers @{ 'x-agentsentry-key' = $adminKey }
  Ok 'Self-test passed'
} catch {
  Warn "self-test request failed: $($_.Exception.Message)"
}

# 9. final user-facing instructions ------------------------------------
$gw = "http://localhost:$GatewayPort"
$ui = "http://localhost:$UiPort"
Write-Host ''
Write-Host '================ AgentSentry is ready ================' -ForegroundColor Green
Write-Host ''
Write-Host "  UI:        $ui"
Write-Host "  Gateway:   $gw"
Write-Host "  Control:   http://localhost:$ControlPort"
Write-Host ''
Write-Host '  Tenant API key (point your agent SDKs at this):' -ForegroundColor Yellow
Write-Host "    $tenantKey"
Write-Host ''
Write-Host '  Admin API key (UI / control-plane only — do NOT ship to agents):' -ForegroundColor Yellow
Write-Host "    $adminKey"
Write-Host ''
Write-Host '------- AGENT-SIDE STEPS (manual) -------' -ForegroundColor Cyan
Write-Host '  1. Change your LLM client base URL:'
if ($useOpenAI)    { Write-Host "       OpenAI    -> $gw/v1/openai" }
if ($useAnthropic) { Write-Host "       Anthropic -> $gw/v1/anthropic" }
if ($useGemini)    { Write-Host "       Gemini    -> $gw/v1/gemini" }
if ($useAzure)     { Write-Host "       Azure     -> $gw/v1/azure" }
Write-Host '  2. Add header on every request:'
Write-Host '       x-agentsentry-key:   <tenant key above>'
Write-Host '       x-agentsentry-agent: <your agent id, e.g. support-bot>'
Write-Host '  3. Open the UI -> Onboarding tab for copy-paste SDK snippets.'
Write-Host ''
Write-Host '  Full config guide: docs/install.md' -ForegroundColor Cyan
Write-Host '======================================================' -ForegroundColor Green
