#!/usr/bin/env bash
# AgentSentry one-shot installer (Linux/macOS).
#
# Usage:
#   ./install.sh                       # interactive
#   ./install.sh --non-interactive     # accept all defaults
#   ./install.sh --profile prod        # use prod preset
#   ./install.sh --skip-boot           # render config only

set -euo pipefail
ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

PROFILE="dev"
NONINTERACTIVE=0
SKIP_BOOT=0
GATEWAY_PORT=8080
CONTROL_PORT=8081
UI_PORT=3000

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile)         PROFILE="$2"; shift 2 ;;
    --non-interactive) NONINTERACTIVE=1; shift ;;
    --skip-boot)       SKIP_BOOT=1; shift ;;
    --gateway-port)    GATEWAY_PORT="$2"; shift 2 ;;
    --control-port)    CONTROL_PORT="$2"; shift 2 ;;
    --ui-port)         UI_PORT="$2"; shift 2 ;;
    -h|--help)
      sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

c_cyan="\033[36m"; c_green="\033[32m"; c_yellow="\033[33m"; c_red="\033[31m"; c_reset="\033[0m"
info() { printf "${c_cyan}[i]${c_reset} %s\n" "$*"; }
ok()   { printf "${c_green}[+]${c_reset} %s\n" "$*"; }
warn() { printf "${c_yellow}[!]${c_reset} %s\n" "$*"; }
fail() { printf "${c_red}[x]${c_reset} %s\n" "$*"; exit 1; }

ask() {
  local prompt="$1" default="$2" reply
  if [[ $NONINTERACTIVE -eq 1 ]]; then echo "$default"; return; fi
  read -r -p "$prompt [$default]: " reply || true
  echo "${reply:-$default}"
}
ask_yn() {
  local prompt="$1" default="$2" reply
  local d="N"; [[ "$default" == "1" ]] && d="Y"
  if [[ $NONINTERACTIVE -eq 1 ]]; then echo "$default"; return; fi
  read -r -p "$prompt [$d/n]: " reply || true
  reply="${reply:-$d}"
  case "${reply,,}" in y|yes|true|1) echo 1 ;; *) echo 0 ;; esac
}
new_secret() { echo "sk_$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"; }

cat <<'BANNER'

  ___                  _   ____             _
 / _ \                | | / ___|  ___ _ __ | |_ _ __ _   _
/ /_\ \ __ _  ___ _ __| |_\___ \ / _ \  _ \| __|  __| | | |
|  _  |/ _` |/ _ \  _ \ __|___) |  __/ | | | |_| |  | |_| |
\_| |_/\__, |\___/_| |_\__|____/ \___|_| |_|\__|_|   \__, |
        |___/                                         |___/

BANNER
info "Installing AgentSentry into $ROOT"
echo

command -v docker >/dev/null || fail "docker is required"
docker compose version >/dev/null 2>&1 || fail "'docker compose' v2 plugin is required"
ok "docker + docker compose detected"

info "Collecting configuration. Press Enter to accept the default."
ORG=$(ask        "Organization name"               "Acme")
ADMIN_EMAIL=$(ask "Admin email"                    "admin@example.com")

DEF_OPENAI=$([[ "$PROFILE" == "dev" ]] && echo 1 || echo 0)
USE_OPENAI=$(ask_yn "Enable OpenAI proxy?"    "$DEF_OPENAI")
OPENAI_BASE=""; [[ $USE_OPENAI == 1 ]] && OPENAI_BASE=$(ask "OpenAI base URL"    "https://api.openai.com")

USE_ANTHROPIC=$(ask_yn "Enable Anthropic proxy?" "1")
ANTHROPIC_BASE=""; [[ $USE_ANTHROPIC == 1 ]] && ANTHROPIC_BASE=$(ask "Anthropic base URL" "https://api.anthropic.com")

USE_GEMINI=$(ask_yn "Enable Google Gemini proxy?" "1")
GEMINI_BASE=""; [[ $USE_GEMINI == 1 ]] && GEMINI_BASE=$(ask "Gemini base URL" "https://generativelanguage.googleapis.com")

USE_AZURE=$(ask_yn "Enable Azure OpenAI proxy?" "0")
AZURE_BASE=""; [[ $USE_AZURE == 1 ]] && AZURE_BASE=$(ask "Azure OpenAI resource URL" "https://YOUR-RESOURCE.openai.azure.com")

REDACT_LEVEL=$(ask "Redaction level (off|standard|strict)" "standard")
DEF_POLICY=$([[ "$PROFILE" == "prod" ]] && echo "strict" || echo "standard")
POLICY_PACK=$(ask "Starter policy pack (open|standard|strict)" "$DEF_POLICY")

ADMIN_KEY=$(new_secret)
TENANT_KEY=$(new_secret)
ok "Generated admin + tenant API keys"

ENV_FILE="$ROOT/.env.agentsentry"
cat > "$ENV_FILE" <<EOF
# Auto-generated by install.sh on $(date -u +%FT%TZ)
# Do NOT commit. Treat the keys below as production secrets.
SENTRY_ORG_NAME=$ORG
SENTRY_ADMIN_EMAIL=$ADMIN_EMAIL
SENTRY_ADMIN_API_KEY=$ADMIN_KEY
SENTRY_TENANT_API_KEY=$TENANT_KEY

SENTRY_GATEWAY_PORT=$GATEWAY_PORT
SENTRY_CONTROL_PORT=$CONTROL_PORT
SENTRY_UI_PORT=$UI_PORT

SENTRY_REDACT_LEVEL=$REDACT_LEVEL
SENTRY_POLICY_PACK=$POLICY_PACK

SENTRY_GW_OPENAI_BASE_URL=$OPENAI_BASE
SENTRY_GW_ANTHROPIC_BASE_URL=$ANTHROPIC_BASE
SENTRY_GW_GEMINI_BASE_URL=$GEMINI_BASE
SENTRY_GW_AZURE_BASE_URL=$AZURE_BASE
EOF
ok "Wrote $ENV_FILE"

ENABLE_PII="true"; [[ "$REDACT_LEVEL" == "off" ]] && ENABLE_PII="false"
ENABLE_SEC="$ENABLE_PII"

UPSTREAMS=""
[[ $USE_OPENAI    == 1 ]] && UPSTREAMS+="  openai:\n    base_url: \"$OPENAI_BASE\"\n"
[[ $USE_ANTHROPIC == 1 ]] && UPSTREAMS+="  anthropic:\n    base_url: \"$ANTHROPIC_BASE\"\n"
[[ $USE_GEMINI    == 1 ]] && UPSTREAMS+="  gemini:\n    base_url: \"$GEMINI_BASE\"\n"
[[ $USE_AZURE     == 1 ]] && UPSTREAMS+="  azure:\n    base_url: \"$AZURE_BASE\"\n"

cat > "$ROOT/gateway/config.generated.yaml" <<EOF
# generated by install.sh -- safe to regenerate
listen_addr: "0.0.0.0:8080"
control_plane_url: "http://control:8081"
api_key: "$ADMIN_KEY"
poll_interval_seconds: 10

redact:
  enable_pii:     $ENABLE_PII
  enable_secrets: $ENABLE_SEC

upstreams:
$(printf "$UPSTREAMS")
EOF
ok "Wrote gateway/config.generated.yaml"

SEED="true"; [[ "$PROFILE" == "prod" ]] && SEED="false"
cat > "$ROOT/control/config.generated.yaml" <<EOF
# generated by install.sh -- safe to regenerate
listen_addr: ":8081"
postgres_dsn: "postgres://sentry:sentry@postgres:5432/sentry?sslmode=disable"
clickhouse_dsn: "clickhouse://default:@clickhouse:9000/sentry"
dev_api_key: "$ADMIN_KEY"
seed_demo_data: $SEED
policy_pack: "$POLICY_PACK"
EOF
ok "Wrote control/config.generated.yaml"

cat > "$ROOT/deploy/docker-compose.generated.yml" <<EOF
# generated by install.sh -- merged with deploy/docker-compose.dev.yml
services:
  control:
    environment:
      SENTRY_DEV_API_KEY: "$ADMIN_KEY"
      SENTRY_SEED_DEMO:   "$SEED"
      SENTRY_POLICY_PACK: "$POLICY_PACK"
    ports: ["${CONTROL_PORT}:8081"]
  gateway:
    environment:
      SENTRY_GW_CONTROL_URL: "http://control:8081"
      SENTRY_GW_API_KEY:     "$ADMIN_KEY"
      SENTRY_GW_OPENAI_BASE_URL:    "$OPENAI_BASE"
      SENTRY_GW_ANTHROPIC_BASE_URL: "$ANTHROPIC_BASE"
      SENTRY_GW_GEMINI_BASE_URL:    "$GEMINI_BASE"
      SENTRY_GW_AZURE_BASE_URL:     "$AZURE_BASE"
      RUST_LOG: "info"
    ports: ["${GATEWAY_PORT}:8080"]
  ui:
    environment:
      CONTROL_API_URL: "http://control:8081"
      CONTROL_API_KEY: "$ADMIN_KEY"
    ports: ["${UI_PORT}:3000"]
EOF
ok "Wrote deploy/docker-compose.generated.yml"

if [[ $SKIP_BOOT -eq 1 ]]; then ok "Skipping boot (--skip-boot)."; exit 0; fi

info "Booting docker stack (this builds the first time, ~3-5 min)..."
docker compose \
  -f deploy/docker-compose.dev.yml \
  -f deploy/docker-compose.generated.yml \
  up -d --build

wait_http() {
  local url="$1" deadline=$(( $(date +%s) + ${2:-120} ))
  while [[ $(date +%s) -lt $deadline ]]; do
    if curl -fsS -m 2 "$url" >/dev/null 2>&1; then return 0; fi
    sleep 2
  done
  return 1
}
info "Waiting for control plane..."
wait_http "http://localhost:$CONTROL_PORT/v1/health" || fail "control plane never came up"
ok "Control plane healthy"
info "Waiting for gateway..."
wait_http "http://localhost:$GATEWAY_PORT/healthz"   || fail "gateway never came up"
ok "Gateway healthy"

info "Self-test: sending a policy probe..."
if curl -fsS -X POST "http://localhost:$GATEWAY_PORT/v1/policy/check" \
  -H "content-type: application/json" \
  -H "x-agentsentry-key: $ADMIN_KEY" \
  -d '{"package":"agentsentry.llm_call","input":{"request":{"body":{"probe":true}}}}' >/dev/null; then
  ok "Self-test passed"
else
  warn "Self-test request failed (the stack is up but policy check did not respond)."
fi

GW="http://localhost:$GATEWAY_PORT"
UI="http://localhost:$UI_PORT"
cat <<EOF

${c_green}================ AgentSentry is ready ================${c_reset}

  UI:        $UI
  Gateway:   $GW
  Control:   http://localhost:$CONTROL_PORT

  ${c_yellow}Tenant API key${c_reset} (point your agent SDKs at this):
    $TENANT_KEY

  ${c_yellow}Admin API key${c_reset} (UI / control-plane only -- do NOT ship to agents):
    $ADMIN_KEY

  ${c_cyan}------- AGENT-SIDE STEPS (manual) -------${c_reset}
  1. Change your LLM client base URL:
EOF
[[ $USE_OPENAI    == 1 ]] && echo "       OpenAI    -> $GW/v1/openai"
[[ $USE_ANTHROPIC == 1 ]] && echo "       Anthropic -> $GW/v1/anthropic"
[[ $USE_GEMINI    == 1 ]] && echo "       Gemini    -> $GW/v1/gemini"
[[ $USE_AZURE     == 1 ]] && echo "       Azure     -> $GW/v1/azure"
cat <<EOF
  2. Add header on every request:
       x-agentsentry-key:   <tenant key above>
       x-agentsentry-agent: <your agent id, e.g. support-bot>
  3. Open the UI -> Onboarding tab for copy-paste SDK snippets.

  Full config guide: docs/install.md
${c_green}======================================================${c_reset}
EOF
